export class OperationKeywords {
  public static readonly values: string[] = [
    "ANDERE/SONSTIGE", "ALARMIERUNG BEZ", "ALARMIERUNG LEZ", "ALTERSHEIM", "ANDERE-SONSTIGE",
    "ANFORDERUNG LEITER/STEIGER", "ANFORDERUNG SONDERFAHRZEUG", "ANFORDERUNG SONDERGERÄT",
    "AST/BAUM/BAUTEIL", "AUFSTIEGSANLAGEN", "AUSFALL TELEFON/STROM", "BAUSTELLE",
    "BERGUNG FAHRZEUG", "BERGUNG SCHWERFAHRZEUG", "BRAND MIT ATOMAREN GEFAHREN",
    "BRAND MIT BIOLOGISCHEN GEFAHREN", "BRAND MIT CHEMISCHEN GEFAHREN", "BRENNSTOFFLAGER",
    "BÜRO/DIENSTLEISTUNG", "DEICHWACHE", "EISENBAHN", "EISENBAHNUNFALL", "ELEKTROANLAGE",
    "ENTSCHEIDUNG EINSATZ LNZ ANRUFEN", "ENTSCHEIDUNG SUCHAKTION", "ERDRUTSCH/STEINSCHLAG",
    "EXPLOSION", "FAHRZEUG", "FELSSTURZ", "FLUGZEUGABSTURZ", "GASAUSTRITT IM FREIEN",
    "GASAUSTRITT IM GEBÄUDE", "GASGERUCH IM GEBÄUDE", "GASGERUCH IN FREIEN", "GEBÄUDEEINSTURZ",
    "GROSSTIERRETTUNG", "HANDEL/LAGER", "HANDWERK", "HOTEL GASTGEWERBE", "IM FREIEN", "IN GEBÄUDE",
    "INDUSTRIE", "INSEKTENBEKÄMPFUNG", "KAMIN", "KLÄRANLAGE", "KRANKENHAUS", "LANDWIRTSCHAFT",
    "LAWINENABGANG", "LAWINENABGANG OHNE PERSONEN", "LKW/BUS", "LOTSENDIENST RTH", "MASSENUNFALL",
    "MEHRERE KFZ", "MELDERALARM", "MÜLLCONTAINER", "MÜLLDEPONIE", "OBSTMAGAZIN", "ÖL GEWÄSSER",
    "ÖLUNFALL", "PEGELMESSSTELLE", "PERSON EINGEKLEMMT", "PERSON IM WASSER", "PERSON IN AUFZUG",
    "PERSON IN GEFAHR", "PERSON UNTER KFZ", "PERSON UNTER ZUG", "PERSON VERSCHÜTTET", "PKW IM WASSER",
    "RAUCHENTWICKLUNG", "RECYCLINGHOF", "REINIGUNG KANAL", "SCHULE/KINDERGARTEN", "SICHERN/ABSPERREN",
    "STRASSENREINIGUNG", "STROMUNFALL", "SUCHE UND BERGUNG IM WASSER", "TANKSTELLE",
    "TECHN EINSATZ ATOMARE GEFAHREN", "TECHN EINSATZ BIOLOG GEFAHREN", "TECHN EINSATZ CHEMISCHE GEFAHREN",
    "TIEFGARAGE", "TIERRETTUNG", "TÜRÖFFNUNG", "TUNNEL", "ÜBERSCHWEMMUNG",
    "UNTERSTÜTZUNG ANDERE ORGANISATION", "UNWETTER", "VERANSTALTUNGSORT", "VU BUS MIT EINGEKL PERSONEN",
    "VU BUS OHNE EINGEKL PERSONEN", "VU LKW MIT EINGEKLEMMTEN PERSONEN", "VU LKW OHNE EINGEKL PERSONEN",
    "VU MEHRERE LKW", "VU MIT EINGEKLEMMTEN PERSONEN", "VU OHNE VERLETZTE PERSONEN",
    "VU MIT VERLETZTEN PERSONEN", "WALD", "WASSERSCHADEN", "WIESE/BÖSCHUNG", "WOHNGEBÄUDE"
  ];
}
